version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar
